/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/password-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 비밀번호 변경
         * @description 현재 비밀번호를 확인한 후 새 비밀번호로 변경합니다. JWT 토큰이 필요합니다.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchBoards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mypage/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 로그인된 사용자를 로그아웃합니다. 세션을 무효화합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mypage/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로필 통합 수정
         * @description 기존에 분리되어 있던 이미지, 닉네임, 주소 변경을 한 번에 처리하는 API입니다. 변경을 원하는 필드 값(FormData 형식)만 채워서 보내면 됩니다. 변경하지 않을 값은 빈 값으로 두거나 안 보내도 됩니다. JWT 토큰이 필수입니다.
         */
        post: operations["editProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 새 게시물 생성
         * @description 새로운 옷 대여 게시물을 작성. (토큰 인증 필수)
         */
        post: operations["createBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 신규 사용자를 등록. 이메일, 닉네임, 비밀번호, 주소 정보가 필요.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 임시 비밀번호 발급
         * @description 등록된 이메일로 임시 비밀번호를 생성하여 전송합니다. 기존 비밀번호는 임시 비밀번호로 변경됩니다.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mypage/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 마이페이지 프로필 조회
         * @description 현재 로그인된 사용자의 프로필 정보를 조회합니다. (닉네임, 주소, 이메일) JWT 토큰이 필요합니다.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mypage/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 상품 목록 조회
         * @description 현재 로그인된 유저가 업로드(등록)한 모든 상품(옷) 목록을 불러옴.
         *
         *      이메일(JWT 토큰)을 기반으로 본인이 올린 게시물만 출력하며, 상태(판매중 등)와 사진 정보가 포함.
         */
        get: operations["getMyProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/shoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getShoes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/outher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOuter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/onepiece": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOnePieces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/jewelry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJewelry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/bottom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBottoms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/All": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao/login-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카카오 로그인 URL 조회
         * @description 프론트에서 이 URL로 리다이렉트하면 카카오 로그인 페이지가 열립니다.
         */
        get: operations["getKakaoLoginUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카카오 로그인 콜백
         * @description 카카오에서 인가 코드를 받아 로그인 처리 후 JWT 토큰을 반환합니다.
         */
        get: operations["kakaoCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["protectedEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 현재 로그인된 사용자의 계정을 삭제합니다. JSON 바디로 'password'를 보내서 비밀번호가 일치해야 탈퇴됩니다. 관련된 게시글 및 데이터도 함께 삭제됩니다.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 비밀번호 변경 요청 DTO */
        PasswordChangeRequestDto: {
            /**
             * @description 현재 비밀번호
             * @example currentPassword123
             */
            currentPassword: string;
            /**
             * @description 새 비밀번호
             * @example newPassword456
             */
            newPassword: string;
        };
        BoardSearchRequestDto: {
            title?: string;
            description?: string;
            sex?: string;
            size?: string;
            place?: string;
        };
        BoardSearchResponseDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            rentalPeriod?: number;
            /** Format: int32 */
            rentalCost?: number;
            location?: string;
            imageUrl?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 게시물 생성 요청 DTO */
        BoardCreateRequestDto: {
            /**
             * @description 게시물 제목
             * @example 나이키 바람막이 L사이즈 빌려드려요!
             */
            title?: string;
            /**
             * @description 게시물 상세 설명
             * @example 1회 실착 완전 새상품급입니다. 비 오는 날 입기 좋아요.
             */
            description?: string;
            /**
             * Format: binary
             * @description 게시물 이미지 파일 (첨부 안 할 시 기본 이미지 등록됨)
             */
            image?: string;
            /**
             * @description 옷 사이즈 (예: S, M, L, XL, Free)
             * @example L
             */
            size?: string;
            /**
             * @description 성별 (예: M, W, 공용)
             * @example 공용
             */
            sex?: string;
            /**
             * @description 거래 희망 장소 (직거래 시)
             * @example 강남역 2번 출구 앞
             */
            place?: string;
            /**
             * Format: int64
             * @description 대여 가격 (원 단위)
             * @example 15000
             */
            price?: number;
            /**
             * Format: int32
             * @description 대여 기간 (일 수)
             * @example 3
             */
            date?: number;
            /**
             * @description 옷 카테고리 (tops, bottom, outher, onepiece, jewelry, shoes 중 택 1)
             * @example outher
             */
            category?: string;
        };
        BoardCreateResponsetDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            image?: string;
            size?: string;
            sex?: string;
            place?: string;
            /** Format: int32 */
            date?: number;
            category?: string;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createAt?: string;
        };
        /** @description 회원가입 요청 DTO */
        UserCreateRequestDto: {
            /**
             * @description 사용자 이메일 주소(고유해야함)
             * @example user@example.com
             */
            email: string;
            /**
             * @description 사용자 닉네임 (고유해야 함)
             * @example 홍길동
             */
            nickname: string;
            /**
             * @description 사용자 비밀번호
             * @example password123
             */
            password: string;
            /**
             * @description 사용자 주소
             * @example 부산시 부산진구
             */
            address?: string;
        };
        /** @description 회원가입 응답 DTO */
        UserResponeDto: {
            /**
             * @description 등록된 사용자 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 등록된 사용자 닉네임
             * @example 김영진
             */
            nickname?: string;
            /**
             * @description 등록된 사용자 주소
             * @example 부산시 부산진구
             */
            address?: string;
            /**
             * @description 등록된 사용자 프로필 이미지 경로
             * @example https://opencloset.jihongeek.workers.dev/images/default_profile.png
             */
            profileImage?: string;
        };
        RefreshTokenRequestDto: {
            refreshToken?: string;
        };
        TokenRefreshResponseDto: {
            accessToken?: string;
        };
        PasswordResetRequestDto: {
            email?: string;
        };
        LoginRequestDto: {
            email?: string;
            password?: string;
        };
        LoginResponseDto: {
            email?: string;
            nickname?: string;
            message?: string;
            accessToken?: string;
            refreshToken?: string;
            profileImage?: string;
        };
        /** @description 마이페이지 프로필 조회 응답 DTO */
        MyPageProfileResponseDto: {
            /**
             * @description 사용자 닉네임
             * @example UserName
             */
            nickname?: string;
            /**
             * @description 사용자 주소
             * @example 부산 진구 가야동
             */
            address?: string;
            /**
             * @description 사용자 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 프로필 이미지 경로
             * @example /uploads/profiles/default.jpg
             */
            profileImage?: string;
        };
        /** @description 내 상품 목록 응답 DTO */
        MyProductResponseDto: {
            /**
             * Format: int64
             * @description 상품 ID
             * @example 1
             */
            productId?: number;
            /**
             * @description 상품 제목
             * @example 나이키 에어맥스 90
             */
            title?: string;
            /**
             * Format: int32
             * @description 상품 가격
             * @example 50000
             */
            price?: number;
            /**
             * @description 상품 상태 (판매중, 예약중, 판매완료)
             * @example 판매중
             */
            status?: string;
            /**
             * @description 상품 이미지 URL
             * @example https://example.com/image.jpg
             */
            imageUrl?: string;
            /**
             * @description 등록 일시
             * @example 2026-03-19T10:00:00
             */
            createdAt?: string;
        };
        TopsResponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            image?: string;
            size?: string;
            sex?: string;
            place?: string;
            /** Format: int32 */
            date?: number;
            category?: string;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createAt?: string;
        };
        ShoesResponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            image?: string;
            size?: string;
            sex?: string;
            place?: string;
            /** Format: int32 */
            date?: number;
            category?: string;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createAt?: string;
        };
        OutherResponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            image?: string;
            size?: string;
            sex?: string;
            place?: string;
            /** Format: int32 */
            date?: number;
            category?: string;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createAt?: string;
        };
        One_pieceResponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            image?: string;
            size?: string;
            sex?: string;
            place?: string;
            /** Format: int32 */
            date?: number;
            category?: string;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createAt?: string;
        };
        JewelryResponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            image?: string;
            size?: string;
            sex?: string;
            place?: string;
            /** Format: int32 */
            date?: number;
            category?: string;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createAt?: string;
        };
        BottomsReponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            image?: string;
            size?: string;
            sex?: string;
            place?: string;
            /** Format: int32 */
            date?: number;
            category?: string;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequestDto"];
            };
        };
        responses: {
            /** @description 비밀번호 변경 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "비밀번호가 성공적으로 변경되었습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 현재 비밀번호 불일치 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "error": "Bad Request",
                     *       "message": "현재 비밀번호가 일치하지 않습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 인증되지 않은 사용자 (토큰 없음 또는 만료) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    searchBoards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardSearchRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardSearchResponseDto"][];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "로그아웃 성공!"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 인증되지 않은 사용자 (토큰 없음 또는 만료) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    editProfile: {
        parameters: {
            query?: {
                nickname?: string;
                address?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    profileImage?: string;
                };
            };
        };
        responses: {
            /** @description 프로필 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "프로필 정보가 성공적으로 수정되었습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 잘못된 요청 또는 닉네임 중복 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "이미 사용 중인 닉네임입니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 인증되지 않은 사용자 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    createBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["BoardCreateRequestDto"];
            };
        };
        responses: {
            /** @description 게시물 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardCreateResponsetDto"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequestDto"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponeDto"];
                };
            };
            /** @description 이미 존재하는 이메일 또는 닉네임 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenRefreshResponseDto"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestDto"];
            };
        };
        responses: {
            /** @description 임시 비밀번호 전송 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "임시 비밀번호가 이메일로 전송되었습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 등록되지 않은 이메일 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "error": "Bad Request",
                     *       "message": "사용자를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 프로필 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPageProfileResponseDto"];
                };
            };
            /** @description 인증되지 않은 사용자 (토큰 없음 또는 만료) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getMyProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 내 상품 목록 조회 완벽히 성공! */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "productId": 25,
                     *         "title": "나이키 바람막이 L사이즈 빌려드려요!",
                     *         "price": 15000,
                     *         "status": "판매중",
                     *         "imageUrl": "https://opencloset.jihongeek.com/uploads/boards/17150123984_nike_windbreaker.jpg",
                     *         "createdAt": "2026-03-24T18:30:11.123"
                     *       },
                     *       {
                     *         "productId": 11,
                     *         "title": "아디다스 츄리닝 바지",
                     *         "price": 8000,
                     *         "status": "예약중",
                     *         "imageUrl": "https://opencloset.jihongeek.com/images/default_board.png",
                     *         "createdAt": "2026-03-10T12:00:00.000"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["MyProductResponseDto"][];
                };
            };
            /** @description 로그인하지 않았거나 토큰이 만료됨 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unauthorized - 유효하지 않은 토큰입니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardCreateResponsetDto"];
                };
            };
        };
    };
    getTops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopsResponseDto"][];
                };
            };
        };
    };
    getShoes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShoesResponseDto"][];
                };
            };
        };
    };
    getOuter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OutherResponseDto"][];
                };
            };
        };
    };
    getOnePieces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["One_pieceResponseDto"][];
                };
            };
        };
    };
    getJewelry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JewelryResponseDto"][];
                };
            };
        };
    };
    getBottoms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BottomsReponseDto"][];
                };
            };
        };
    };
    getPosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardCreateResponsetDto"][];
                };
            };
        };
    };
    getKakaoLoginUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 카카오 로그인 URL 반환 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    kakaoCallback: {
        parameters: {
            query: {
                /** @description 카카오에서 전달받은 인가 코드 */
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 카카오 로그인 성공, JWT 토큰 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description 카카오 로그인 처리 중 오류 발생 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    protectedEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 탈퇴를 위한 비밀번호 입력 */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "password": "mySecret123!"
                 *     }
                 */
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description 회원 탈퇴 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "회원탈퇴가 완료되었습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 비밀번호 불일치 또는 누락 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "비밀번호가 일치하지 않습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 인증되지 않은 사용자 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "message": "Unauthorized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
}
